plugins {
    id 'groovy'
}

project.ext {
    VERSION = "0.1.0"
    GROOVY_VERSION = "3.0.10"
    mainClassName = 'SimulateCNVs'
}

repositories {
    mavenCentral()
    maven {
        name "biojava"
        url "https://www.biojava.org/download/maven/"
    }
}

dependencies {
    implementation group: 'org.codehaus.groovy', name: 'groovy', version: "$GROOVY_VERSION"
    implementation group: 'org.codehaus.groovy', name: 'groovy-xml', version: "$GROOVY_VERSION"
    implementation group: 'org.codehaus.groovy', name: 'groovy-ant', version: "$GROOVY_VERSION"
    implementation group: 'org.codehaus.groovy', name: 'groovy-json', version: "$GROOVY_VERSION"
    implementation group: 'org.codehaus.groovy', name: 'groovy-sql', version: "$GROOVY_VERSION"

    implementation group: 'com.googlecode.lanterna', name: 'lanterna', version: '3.0.0-beta3'

    implementation 'org.codehaus.gpars:gpars:0.12'

    implementation files('tools/groovy-ngs-utils/1.0.9/groovy-ngs-utils.jar')

    testImplementation 'junit:junit:4.13.2'
}

test {
    testLogging {
        events "passed", "skipped", "failed"
    }
}

jar {
    from configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }

    manifest {
        attributes 'Main-Class': mainClassName
    }
}
